### PR TITLE
Pull request to get Codeclimate metrics

### PR DESCRIPTION
**Pull request by eoptam**

### CODE REVIEW

**Comment by eoptam** [comment]
Hey Alex,

it seems that codeclimate is not configured for the "master" and "team2" branch, could you adjust that so we get codeclimate results?

image

Cheers

**Comment by eoptam** [comment]
Ah my mistake, master seems to be present, but somehow the tests don't show up. Just the tests/test_sample.py

**Comment by akb89** [comment]
Ok I found the bug: the last command in travis does not pass:
```
after_success:
  - env CODECLIMATE_REPO_TOKEN=e6b2f4aa476b513fbe5f43fb29104dee1f0a24cb10d19de1b966a988397bdf7f codeclimate-test-reporter
```
Probably because of the line break. This command is supposed to send the test coverage metrics to code climate. I'm on it

**Comment by akb89** [comment]
Actually, the bug was related to climat.py version. It's now fixed.

**Pull request merged**
